//
// HVSC Update Tool
//
// Copyright (C) 1998,1999 HVSC administrators.

#include <ctype.h>
#include <sys/stat.h>
#include <sys/types.h>

#include <cstdlib>
#include <fstream>

#include "config.h"
using std::ifstream;

#include <iomanip>
using std::ios;

#include <iostream>
using std::cerr;
using std::cin;
using std::cout;
using std::endl;

#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <filesystem>
namespace fs = std::filesystem;

#if defined(_MSC_VER)
#include <windows.h>
#endif

#if defined(HAVE_LINUX) || defined(HAVE_UNIX) || defined(HAVE_BEOS)
#include <unistd.h>
#endif

#include "MoveReplace.h"
#include "PathSplitter.h"
#include "TextFile.h"
#include "fastperc.h"
#include "fformat.h"
#include "helpers.h"
#include "hvscver.h"
#include "sidtune.h"

// Defines the version, generated by CMake
#include <update_tool_version.h>

static const char versionString[] = HVSC_VERSION_STRING;
static const char HVSCcontactEmail[] = "HVSC Admin <hvsc@c64.org>";

HVSCVER HVSCversion_found;

static const bool ALLOW_PRE_UPDATE7 = false;

// HVSC top-level directories. Case does not matter because it
// will be determined by the update tool.
static const char UPDATE_DIR[] = "update";
//
// HVSC 2.0-post (long file names)
static const char LONG_DOCUMENTS_DIR[] = "DOCUMENTS";
static const char LONG_HUBBARD_ROB_DIR_PRE46[] = "Hubbard_Rob";
static const char LONG_HUBBARD_ROB_DIR[] = "MUSICIANS/H/Hubbard_Rob";

// The main HVSC doc file is read by the revision check code.
static const char HVSIDS_TXT[] = "HVSC.txt";
static const char OLD_HVSIDS_TXT[] = "hv_sids.txt";

static const char* DOCUMENTS_DIR = LONG_DOCUMENTS_DIR;
static const char* HUBBARD_ROB_DIR = LONG_HUBBARD_ROB_DIR;

static const int maxUpdateNum = 1000;  // Should be plenty...
static const int maxSidInfoLen = 32;   // not including terminator

#include "Mode.h"

static Mode mode = Mode::NO_MODE;

// We include it here because it depends on above mode_type.
#include "mysidtune.h"

static TextFile updateFile(0);

void logError(ofstream& errorFile, std::string lineContent,
              std::string errorMessage, int iLineNum, Mode mode,
              int& errorCount);

ErrorLogger mkErrorLogger(ofstream& errorFile, Mode mode, int& errorCount) {
  return [mode, &errorCount, &errorFile](
             std::string lineContent, std::string errorMessage, int lineNum) {
    logError(errorFile, lineContent, errorMessage, lineNum, mode, errorCount);
  };
}

bool myMkDir(const char* dirName);

bool isDir(const char* fileName);

// Returns false if user prompting is disabled by setting the HVSC_NO_PROMPT
// environment variable. This is to facilitate automated testing.
bool prompt_user() {
  auto str = std::getenv("HVSC_NO_PROMPT");
  return str == nullptr;
}

// Until we add fmt/std::format, this will do
std::string numToStr(int value, int width) {
  std::ostringstream oss;
  oss << std::setw(width) << std::setfill('0') << value;
  return oss.str();
}

// --------------------------------------------------------------------------
// OS-dependent application exit() wrapper.

inline void appExit(int returnValue) {
#if defined(_MSC_VER)
  HANDLE hStdin = GetStdHandle(STD_INPUT_HANDLE);
  DWORD fdwMode, fdwOldMode;
  bool newMode = true;
  if (!GetConsoleMode(hStdin, &fdwOldMode)) newMode = false;
  fdwMode = fdwOldMode & ~(ENABLE_LINE_INPUT | ENABLE_ECHO_INPUT);
  fdwMode |= ENABLE_PROCESSED_INPUT;
  if (!SetConsoleMode(hStdin, fdwMode)) newMode = false;
  // If we could not change console mode, better leave immediately.
  if (newMode) {
    cout << endl << "--- PRESS <RETURN> TO EXIT ---" << endl << flush;
    FlushConsoleInputBuffer(hStdin);
    DWORD count;
    char readBuf[2];
    if (prompt_user()) ReadConsole(hStdin, &readBuf, 1, &count, 0);
    SetConsoleMode(hStdin, fdwOldMode);
  }
#endif
  exit(returnValue);
}

// --------------------------------------------------------------------------

int main(int, char* argv[]) {
#if defined(_MSC_VER)
  SetConsoleTitle("HVSC Update Tool");
#endif

  cout << endl
       << "HVSC Update Tool   Version " << versionString << endl
       << endl;

  struct HVSCversionInfo {
    HVSCVER required;
    HVSCVER resulting;
    HVSCVER found;
    bool havePrevScript;
    bool isHVSC1X;
    bool isUpdate10;
    bool printWarning;
  } HVSCversion;

  HVSCversion.required = MAKE_HVSCVER(0, 0);
  HVSCversion.resulting = MAKE_HVSCVER(0, 0);
  HVSCversion.found = MAKE_HVSCVER(0, 0);
  HVSCversion.isHVSC1X = false;
  HVSCversion.isUpdate10 = false;
  HVSCversion.printWarning = false;

  HVSCversion_found = MAKE_HVSCVER(0, 0);

  // Check whether user is in correct directory inside the HVSC tree.
  // Search for "update" directory.
  fs::path updatePath;
  bool foundUpdateDir = getHVSCpath(updatePath, UPDATE_DIR);

  // Search for "DOCUMENTS" directory.
  fs::path documentsPath;
  bool foundDocumentsDir = false;
  if (getHVSCpath(documentsPath, LONG_DOCUMENTS_DIR)) {
    foundDocumentsDir = true;
    DOCUMENTS_DIR = LONG_DOCUMENTS_DIR;
  }

  cout << "For this tool to work correctly, you must unzip/copy the desired "
          "update"
       << endl
       << "directly within the HVSC main directory (named ``C64music'' if you "
          "haven't"
       << endl
       << "renamed it).  Once you have done this your directory structure "
          "should have"
       << endl
#if defined(_MSC_VER) || defined(__MINGW32__)
       << "a similar path as the following:    C:\\C64music\\update\\" << endl
#else
       << "a similar path as the following:    C64music/update/" << endl
#endif
       << "The device can vary as well as the name of the main HVSC directory."
       << endl
       << "In addition, the main HVSC directory doesn't have to be at the root "
          "of"
       << endl
       << "the selected device." << endl
       << endl
       << "To see exactly what this tool will do to the HVSC, you can view the "
          "file"
       << endl
       << "``UpdateXY.hvs'' (where XY stands for the update number).  That "
          "file is"
       << endl
       << "used for input, but it is written for you to view as well.  It "
          "contains"
       << endl
       << "explanations as to why certain tunes are being replaced, deleted, "
          "etc."
       << endl
       << "The file ``UpdateXY.hvs'' will reside in the ``";
  if (foundDocumentsDir)
    cout << documentsPath;
  else
    cout << DOCUMENTS_DIR;
  cout << "'' directory after" << endl
       << "the tool terminates successfully.  All files in the update "
          "directory will"
       << endl
       << "be removed except the executables.  We recommend that after you "
          "unzip the"
       << endl
       << "collection that you first listen to the tunes before running this "
          "tool."
       << endl
       << "Otherwise, you might have to spend a little more time searching for "
          "them"
       << endl
       << "within the massive collection (you can always re-unzip it later "
          "though)."
       << endl
       << endl
       << "Finally, you must run the tool from within the update directory."
       << endl
       << "(Don't forget to backup your HVSC!)  ";

  cout << "Do you wish to continue? (y/n) : " << flush;

  char cContinue;
  if (prompt_user()) {
    cin >> cContinue;
    cout << endl;
    // Exit if character is anything but 'y' or 'Y'.
    if (tolower(cContinue) != 'y') appExit(0);
  }
  cout << endl;

  // ----------------------------------------------------------------------

  if (!foundDocumentsDir || !foundUpdateDir) {
    if (!foundDocumentsDir) {
      cerr << "Could not locate HVSC documents directory." << endl;
    }
    if (!foundUpdateDir) {
      cerr << "Could not locate HVSC update directory." << endl;
    }
    cerr << endl
         << "Error: " << fileNameWithoutPath(argv[0])
         << " must be run from within the HVSC " << UPDATE_DIR << " directory."
         << endl;
    appExit(-1);
  }

  // ----------------------------------------------------------------------
  // Read the first 10 lines of the main HVSC documentation file
  // and check for the line which contains the version number.

  auto fileNames = {HVSIDS_TXT, OLD_HVSIDS_TXT};
  bool found = false;
  for (auto const& f : fileNames) {
    fs::path hvsidsFileName, hvsidsFileNameTmp;
    hvsidsFileNameTmp.append(DOCUMENTS_DIR).append(f);
    if (getHVSCpath(hvsidsFileName, hvsidsFileNameTmp)) {
      TextFile hvsidsFile(hvsidsFileName.string().c_str());
      int line = 0;
      while (!hvsidsFile.endOfFile() && line <= 10) {
        hvsidsFile.readNextLine();
        line++;
        if (hvsidsFile.isKey("release")) {
          HVSCversion.found = atohvscver(hvsidsFile.getCurParseBuf());
          HVSCversion_found = HVSCversion.found;
        }
      }
      hvsidsFile.close();
      found = true;
      break;
    }
  }
  if (!found) {
    cerr << "Warning: HVSC documentation file ``" << HVSIDS_TXT << "'' or ''"
         << OLD_HVSIDS_TXT << "'' not found." << endl
         << endl;
    HVSCversion.printWarning = true;
  }

  // ----------------------------------------------------------------------

  fs::path errorsFileName;
  fs::path updateFileName, updateFileNameCat;

  int updateNum;
  // Search for the update script.
  for (updateNum = 1; updateNum <= maxUpdateNum; updateNum++) {
    // Update data file is named "UpdateXY.hvs".
    // Work with HVSC-style path names.
    const auto w = updateNum <= 99 ? 2 : 3;
    updateFileNameCat =
        fs::path(UPDATE_DIR)
            .append(std::string("Update") + numToStr(updateNum, w) + ".hvs");
    errorsFileName =
        fs::path(std::string("Errors") + numToStr(updateNum, w) + ".hvs");

    if (getHVSCpath(updateFileName, updateFileNameCat)) {
      break;  // the HVS file has been located
    } else if (updateNum == maxUpdateNum) {
      cerr << "Error: No HVSC update script file ``UpdateXY.hvs'' found."
           << endl;
      appExit(-1);
    }
  }

  // ----------------------------------------------------------------------
  // Extra HVSC structure sanity check.
  // Search for Hubbard directory.
  if (updateNum > 46)
    HUBBARD_ROB_DIR = LONG_HUBBARD_ROB_DIR;
  else if (updateNum > 6)
    HUBBARD_ROB_DIR = LONG_HUBBARD_ROB_DIR_PRE46;

  fs::path hubbardPath;
  if (!getHVSCpath(hubbardPath, HUBBARD_ROB_DIR)) {
    cerr
        << "Rob Hubbard directory not detected!" << endl
        << "Perhaps you did not follow the directions stated at the start of "
           "this "
        << "program?" << endl
        << "The update directory must reside directly in the HVSC directory."
        << endl
        << "Errors will likely occur if you continue (unless you deleted the ``"
        << HUBBARD_ROB_DIR
        << "'' directory and this update does not depend on it)." << endl
        << "Do you wish to continue? (y/n) : " << flush;
    if (prompt_user()) {
      cin >> cContinue;
      // Exit if character is anything but 'y' or 'Y'.
      if (tolower(cContinue) != 'y') appExit(0);
    }
    cout << endl;
  }

  // Count number of lines in file.
  updateFile.open(updateFileName.string().c_str());
  int lines = 0;
  while (!updateFile.endOfFile())  // line-by-line loop
  {
    updateFile.readNextLine();
    lines++;
    if (lines <= 10) {
      if (updateFile.isKey("#PreviousVersion:"))
        HVSCversion.required = atohvscver(updateFile.getCurParseBuf());
      else if (updateFile.isKey("#ResultingVersion:"))
        HVSCversion.resulting = atohvscver(updateFile.getCurParseBuf());
    }
  }
  updateFile.close();

  if (lines == 0) {
    cerr << "HVSC update script file ``" << updateFileName << "'' is empty."
         << endl;
    appExit(-1);
  }

  if (updateNum > 1) {
    // Create the file name of the previous update script,
    // which should be in the DOCUMENTS directory.
    fs::path prevUpdateFileName, prevUpdateFileNameCat;
    const auto w = updateNum - 1 <= 99 ? 2 : 3;
    prevUpdateFileNameCat = fs::path(DOCUMENTS_DIR)
                                .append(std::string("Update") +
                                        numToStr(updateNum - 1, w) + ".hvs");
    HVSCversion.havePrevScript =
        getHVSCpath(prevUpdateFileName, prevUpdateFileNameCat);
    cout << prevUpdateFileNameCat << endl;
  } else {
    HVSCversion.havePrevScript = true;  // Update #1 is first update
  }

  // Version check can be done since Update #7 (HVSC 2.0 => 2.1).
  if (hvscvercmp(HVSCversion.required, MAKE_HVSCVER(0, 0)) > 0 &&
      hvscvercmp(HVSCversion.resulting, MAKE_HVSCVER(0, 0)) > 0) {
    char ver[10];

    hvscvertoa(ver, HVSCversion.required);
    cout.setf(ios::fixed);
    cout << "This update requires HVSC version: " << ver << endl;
    cout << "The update tool has found version: ";
    if (hvscvercmp(HVSCversion.found, MAKE_HVSCVER(0, 0)) > 0) {
      hvscvertoa(ver, HVSCversion.found);
      cout << ver;
    } else {
      cout << "CHECK FAILED";
    }
    cout << endl << endl;
    if (hvscvercmp(HVSCversion.found, HVSCversion.required) != 0) {
      HVSCversion.printWarning = true;
    }
  }

  if (!HVSCversion.havePrevScript) {
    cerr << "Could not find the script from Update #" << dec << setw(2)
         << setfill('0') << updateNum - 1 << " (previous update) in the "
         << endl
         << DOCUMENTS_DIR << " directory. You are about to "
         << "update an incomplete HVSC." << endl
         << endl;
    HVSCversion.printWarning = true;
  }

  if (HVSCversion.printWarning) {
    cout << "***************" << endl
         << "*** WARNING ***" << endl
         << "***************" << endl
         << endl
         << "Errors will likely occur if you continue." << endl
         << "Do you wish to continue? (y/n) : " << flush;
    if (prompt_user()) {
      cin >> cContinue;
      cout << endl;
      // Exit if character is anything but 'y' or 'Y'.
      if (tolower(cContinue) != 'y') appExit(0);
    }
    cout << endl;
  }

  // If Update #10 is used, enable special compatibility mode.
  // Allow missing parameter lines in CREDITS command.
  if (hvscvercmp(HVSCversion.required, MAKE_HVSCVER(2, 3)) == 0 &&
      hvscvercmp(HVSCversion.resulting, MAKE_HVSCVER(2, 4)) == 0) {
    HVSCversion.isUpdate10 = true;
  }

  // This time we take care of file access errors.
  if (!updateFile.open(updateFileName.string().c_str())) {
    cerr << endl
         << "Error: Could not open ``" << updateFileName << "''." << endl;
    appExit(-1);
  }

  ofstream errorFile(errorsFileName.c_str());

  fastPercent updateProgress(lines + 1);
  cout << "Working : ";
  updateProgress.cout();

  // ----------------------------------------------------------------------

  int skipLinesAfterError = 0;
  int errorCount = 0;
  while (!updateFile.endOfFile())  // line-by-line loop
  {
    updateFile.readNextLine();
    updateProgress.update(updateFile.getLineNum());
    if (updateProgress.changed()) updateProgress.coutUpdate();
    // Skip blank and comment lines.
    while (!updateFile.endOfFile() &&
           (updateFile.isBlank() || updateFile.isComment())) {
      updateFile.readNextLine();
    };
    if (updateFile.isBlank()) break;

    // Find the Mode.  Compare current line to all of the keywords
    // until found or end of keywords.
    const auto tmp = std::string{updateFile.getParseBuf()};
    const auto maybeMode = string_to_mode(tmp);

    // If keyword found, get next line in file.
    if (maybeMode.has_value()) {
      mode = maybeMode.value();
      continue;
    }

    int line = updateFile.getLineNum();

    // Based on the mode, take the proper action.
    switch (mode) {
      case Mode::TITLE:
      case Mode::AUTHOR:
      case Mode::RELEASED:
      case Mode::CREDITS:
      case Mode::SPEED:
      case Mode::SONGS:
      case Mode::FIXLOAD:
      case Mode::INITPLAY:
      case Mode::MUSPLAYER:
      case Mode::PLAYSID:
      case Mode::CLOCK:
      case Mode::SIDMODEL:
      case Mode::FREEPAGES:
      case Mode::FLAGS: {
        fs::path tmpSource;
        if (!getHVSCpath(tmpSource, updateFile.getLineBuf())) {
          logError(errorFile, updateFile.getLineBuf(),
                   "File not found or permission denied.", line, mode,
                   errorCount);
          if (mode == Mode::CREDITS)
            skipLinesAfterError = 3;
          else if (mode == Mode::FLAGS)
            skipLinesAfterError = 4;
          else if (mode == Mode::FIXLOAD)
            skipLinesAfterError = 0;
          else
            skipLinesAfterError = 1;
        } else {
          char sidInfo[4][maxSidInfoLen + 1];
          sidInfo[0][0] = 0;
          sidInfo[1][0] = 0;
          sidInfo[2][0] = 0;
          sidInfo[3][0] = 0;

          // strcpy copies terminator.
          // strncpy copies terminator if inside size n.
          // strlen does not count terminator.

          if (Mode::CREDITS == mode) {
            for (int n = 0; n < 3; n++) {
              updateFile.readNextLine();
              if (!HVSCversion.isUpdate10) {
                if (updateFile.isBlank())
                  logError(errorFile, tmpSource.string(),
                           "Premature end of update script?",
                           updateFile.getLineNum(), mode, errorCount);
              }
              if (updateFile.getLineLen() > maxSidInfoLen)
                logError(errorFile, tmpSource.string(),
                         "SID credit string too long.", updateFile.getLineNum(),
                         mode, errorCount);
              strncpy(sidInfo[n], updateFile.getLineBuf(),
                      maxSidInfoLen); /*+1*/
            }
          } else if (Mode::FLAGS == mode) {
            for (int n = 0; n < 4; n++) {
              updateFile.readNextLine();
              if (!HVSCversion.isUpdate10) {
                if (updateFile.isBlank())
                  logError(errorFile, tmpSource.string(),
                           "Premature end of update script?",
                           updateFile.getLineNum(), mode, errorCount);
              }
              strncpy(sidInfo[n], updateFile.getLineBuf(),
                      maxSidInfoLen); /*+1*/
            }
          } else if ((Mode::AUTHOR == mode) || (Mode::TITLE == mode) ||
                     (Mode::RELEASED == mode)) {
            updateFile.readNextLine();
            if (updateFile.isBlank())
              logError(errorFile, tmpSource.string(),
                       "Premature end of update script?",
                       updateFile.getLineNum(), mode, errorCount);
            if (updateFile.getLineLen() > maxSidInfoLen)
              logError(errorFile, tmpSource.string(),
                       "SID credit string too long.", updateFile.getLineNum(),
                       mode, errorCount);
            strncpy(sidInfo[mode_to_int(mode)], updateFile.getLineBuf(),
                    maxSidInfoLen); /*+1*/
          } else if (Mode::FIXLOAD == mode) {
            ;
          }

          // SPEED, SONGS, INITPLAY, MUSPLAYER, PLAYSID, CLOCK,
          // SIDMODEL, FREEPAGES
          else {
            updateFile.readNextLine();
            if (updateFile.isBlank())
              logError(errorFile, tmpSource.string(),
                       "Premature end of update script?",
                       updateFile.getLineNum(), mode, errorCount);
            strncpy(sidInfo[0], updateFile.getLineBuf(), maxSidInfoLen + 1);
          }

          mySidTune sidFile(tmpSource.string().c_str());
          if (!sidFile) {
            logError(errorFile, tmpSource.string(),
                     "Could not load sidtune file.", line, mode, errorCount);
          }
          if (sidFile.writeToSidTune(sidInfo, mode) == true) {
            if (!sidFile.savePSIDfile(tmpSource, true))  // overwrite!
            {
              logError(errorFile, tmpSource.string(),
                       "Could not save sidtune file.", line, mode, errorCount);
            }
          } else {
            logError(errorFile, tmpSource.string(),
                     "Problem writing new sidtune info.", line, mode,
                     errorCount);
          }
        }  // else
        break;
      }

        // -------------------------------------------------------------------
        // DELETE

        // Delete files and directories. Directories being deleted must
        // not have files within it (this might be changed later).

      case Mode::DELETE: {
        fs::path dest;
        const auto src = updateFile.getLineBuf();

        if (!getHVSCpath(dest, src)) {
          logError(errorFile, updateFile.getLineBuf(),
                   "File or directory not found.", line, mode, errorCount);
        } else {
          if (fs::is_directory(dest)) {
            if (std::filesystem::remove(dest) == false) {
              logError(errorFile, dest.string(), "Could not delete directory.",
                       line, mode, errorCount);
            }
          } else {
            if (std::filesystem::remove(dest) == false) {
              logError(errorFile, dest.string(), "Could not delete file.", line,
                       mode, errorCount);
            }
          }
        }
        break;
      }

        // ---------------------------------------------------------------------
        // MOVE

      case Mode::MOVE:
      case Mode::REPLACE: {
        auto err = mkErrorLogger(errorFile, mode, errorCount);
        auto result = move_replace(mode == Mode::MOVE, updateFile, err);
        break;
      }

        // --------------------------------------------------------------------
        // MKDIR

        // Obsolete, but deprecated.

      case Mode::MKDIR: {
        auto err = mkErrorLogger(errorFile, mode, errorCount);

        makeHVSCdir(err, line, updateFile.getLineBuf());
        break;
      }

        // ------------------------------------------------------------------
        // UNKNOWN

        // NO_MODE is active when no keywords have been read yet.

      case Mode::NO_MODE:
      default: {
        logError(errorFile, updateFile.getLineBuf(),
                 "Keyword/parameter mismatch?", line, mode, errorCount);
        break;
      }

    }  // switch

    while (skipLinesAfterError-- > 0) {
      updateFile.readNextLine();
    };
    skipLinesAfterError = 0;

  };  // while !endOfFile

  // ----------------------------------------------------------------------

  updateProgress.end();  // 100%
  cout << endl << endl;

  updateFile.close();

  // Clean up.
  if (errorCount == 0) {
    // Move HVS file.
    PathSplitter docSrc(updateFileNameCat);
    docSrc.lastFile();
    fs::path docDest(documentsPath.c_str());
    docDest.append(docSrc.getFile());
    auto err = mkErrorLogger(errorFile, Mode::NO_MODE, errorCount);
    fileCopy(err, 0, updateFileName.c_str(), docDest.c_str());
  }

  errorFile.close();

  if (errorCount == 0) {
    std::error_code ec;
    fs::remove(updateFileName, ec);
    fs::remove(errorsFileName, ec);

    cout << "Update was successful! Update directory is no longer needed."
         << endl
         << endl
         << "P.S. - Check the update file in the ``" << documentsPath
         << "'' directory for" << endl
         << "answers as to why certain tunes were added (if concerned)."
         << endl;
    appExit(0);
  } else {
    cerr << errorCount << " errors encountered." << endl
         << "Please read ``" << errorsFileName
         << "'', and ``Readme.1st'' in the update archive." << endl
         << "Email " << HVSCcontactEmail
         << " if you encounter any unsolvable problems." << endl;
    appExit(-1);
  }
}

// --------------------------------------------------------------------------

// --------------------------------------------------------------------------

// --------------------------------------------------------------------------

bool myMkDir(const char* dirName) {
  return filesystem_create_directory(dirName);
}

// Try to open a file using opendir(). If successful, it is a directory.
// TODO: can be deleted?
bool isDir(const char* fileName) {
  return std::filesystem::is_directory(fileName);
}

// --------------------------------------------------------------------------

void logError(ofstream& errorFile, std::string lineContent,
              std::string errorMessage, int iLineNum, Mode mode,
              int& errorCount) {
  errorFile << "Line " << iLineNum << ", ";

  errorFile << mode_to_string(mode) << ": ";

  errorFile << errorMessage << endl << "    " << lineContent << endl;

  errorCount++;
  DEBUGGER;
}
